import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import path from "node:path";
import { describe, it } from "node:test";
import type { CypherSchemaContract } from "../src/ir.js";
import { parseCypherLosslessly, roundTripLosslessParse, stripCypherComments } from "../src/lossless-parser.js";

const schema: CypherSchemaContract = {
  version: "cypher-llm-schema/v1",
  dialect: "neo4j-cypher-25",
  nodes: [
    { name: "Tool", properties: { name: { type: "STRING" } } },
    { name: "Hash", properties: { value: { type: "STRING" } } }
  ],
  relationships: [{ type: "has MD5 hash", from: "Tool", to: "Hash" }]
};

describe("lossless Cypher parser", () => {
  it("preserves source bytes while exposing statement, clause, comment, and IR spans", () => {
    const source = [
      "/* generated by model */",
      "MATCH (tool:Tool {name: $toolName})-[:`has MD5 hash`]->(hash:Hash)",
      "// keep the projection exact",
      "RETURN hash.value AS md5 LIMIT 10;",
      ""
    ].join("\n");

    const report = parseCypherLosslessly(source, { schema, parserMode: "syntax" });

    assert.equal(report.roundTrip.ok, true);
    assert.equal(roundTripLosslessParse(report), source);
    assert.equal(report.fragments.map((fragment) => fragment.kind).join(","), "statement,terminator,trivia");
    assert.deepEqual(report.trivia.map((item) => item.kind), ["block-comment", "line-comment"]);
    assert.equal(report.statements.length, 1);
    assert.deepEqual(report.statements[0]?.clauses.map((clause) => clause.keyword), ["MATCH", "RETURN"]);
    assert.equal(report.statements[0]?.clauses[0]?.support, "lifted");
    assert.equal(report.statements[0]?.clauses[0]?.irPath, "/clauses/0");
    assert.ok(report.sourceMap.some((entry) => entry.kind === "fragment" && entry.sourcePath === "/fragments/0"));
    assert.ok(
      report.sourceMap.some(
        (entry) =>
          entry.kind === "trivia" &&
          entry.sourceKind === "line-comment" &&
          entry.sourcePath === "/trivia/1" &&
          entry.text === "// keep the projection exact"
      )
    );
    assert.ok(
      report.sourceMap.some(
        (entry) =>
          entry.kind === "clause" &&
          entry.sourcePath === "/statements/0/clauses/1" &&
          entry.irPath === "/clauses/1" &&
          entry.support === "lifted" &&
          entry.keyword === "RETURN"
      )
    );
    assert.equal(report.irPreview?.supportedClauses, 2);
    assert.equal(report.irPreview?.rawClauses, 0);
    assert.equal(report.irPreview?.parserOk, true);
    assert.equal(report.parser?.ok, true);
  });

  it("keeps unsupported syntax as source-addressable raw clauses", () => {
    const report = parseCypherLosslessly("MATCH (a) USING INDEX a:Person(name) RETURN a", { schema });

    assert.equal(report.roundTrip.ok, true);
    assert.equal(report.statements[0]?.clauses[0]?.keyword, "MATCH");
    assert.equal(report.statements[0]?.clauses[0]?.support, "raw");
    assert.equal(report.sourceMap.find((entry) => entry.sourcePath === "/statements/0/clauses/0")?.support, "raw");
    assert.equal(report.irPreview?.rawClauses, 1);
    assert.ok(report.irPreview?.diagnostics.some((item) => item.code === "raw-lift-unsupported-clause"));
  });

  it("reports unmatched delimiters without losing round-trip data", () => {
    const report = parseCypherLosslessly("MATCH (tool:Tool RETURN tool");

    assert.equal(report.roundTrip.ok, true);
    assert.ok(report.diagnostics.some((item) => item.code === "lossless-unmatched-delimiter"));
    assert.equal(roundTripLosslessParse(report), "MATCH (tool:Tool RETURN tool");
  });

  it("strips comments without touching quoted literals", () => {
    const stripped = stripCypherComments("MATCH (n {x: 'not // comment'}) // comment\nRETURN n");

    assert.equal(stripped, "MATCH (n {x: 'not // comment'}) \nRETURN n");
  });

  it("keeps the checked-in example reproducible", () => {
    const source = readJson<{ source: string }>("examples/lossless/tool-hash.lossless.json").source;
    const expected = readJson("examples/lossless/tool-hash.lossless.json");
    const regenerated = parseCypherLosslessly(source, { schema, parserMode: "syntax" });

    assert.deepEqual(regenerated, expected);
  });
});

function readJson<T = unknown>(relativePath: string): T {
  return JSON.parse(readFileSync(path.join(process.cwd(), relativePath), "utf8")) as T;
}
